# Generated by Django 5.2.11 on 2026-02-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Professeur'), ('admin', 'Administrateur'), ('student', 'Élève'), ('etudiant', 'Étudiant')], default='parent', max_length=15),
        ),
    ]
