# Generated by Django 5.2.11 on 2026-02-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_type', models.CharField(choices=[('single', 'Cours unique'), ('pack_4', 'Pack 4 cours'), ('pack_8', 'Pack 8 cours'), ('monthly', 'Mensuel (12 cours)')], default='single', max_length=10)),
                ('total_sessions', models.PositiveIntegerField()),
                ('used_sessions', models.PositiveIntegerField(default=0)),
                ('price_per_session', models.PositiveIntegerField(help_text='Prix unitaire en FCFA')),
                ('total_price', models.PositiveIntegerField(help_text='Prix total en FCFA')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('exhausted', 'Épuisé'), ('expired', 'Expiré')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_packs', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs_received', to='teachers.teacherprofile')),
            ],
            options={
                'db_table': 'booking_packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('bad_behavior', 'Mauvais comportement'), ('no_show', 'Absence'), ('inappropriate', 'Contenu inapproprié'), ('fraud', 'Fraude'), ('low_quality', 'Qualité insuffisante'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examiné'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='bookings.booking')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
