# Generated by Django 5.2.11 on 2026-03-01 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, help_text="Clé d'idempotence pour éviter les doubles paiements", max_length=100, unique=True),
        ),
    ]
